# Example funding file
# These are some common ways to support open source projects
# Remove any lines that are not applicable

# github: [Razue]
# patreon: your-patreon
# open_collective: your-open-collective
# ko_fi: your-kofi
# tidelift: your-tidelift
# custom: ['https://your.custom.url']
